language: cpp

env:
  global:
    - LINUX_DIST=trusty
    - DEPS_DIR=${TRAVIS_BUILD_DIR}/deps
    - RUN_TESTS=true

matrix:
  include:
    - os: linux
      dist: trusty
      sudo: true
      compiler: gcc
      addons:
       apt:
         packages: &precise_latest_boost_packages
           - gcc-4.8
           - g++-4.8
           - libgtest-dev
         sources: &precise_latest_boost_sources
           - ubuntu-toolchain-r-test
addons:
  apt:
    sources:
      - george-edison55-precise-backports # cmake 3.2.3 / doxygen 1.8.3
    packages:
      - cmake
      - cmake-data

script:
     - cd /usr/src/gtest
     - sudo cmake .
     - sudo make
     - mkdir -p build
     - cd build
     - cmake ../
     - make
     - ./runTests